[package]
name = "remotefs-ssh"
version = "0.8.5"
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
categories = ["network-programming"]
documentation = "https://docs.rs/remotefs-ssh"
edition = "2024"
include = [
  "benches/**/*",
  "examples/**/*",
  "src/**/*",
  "LICENSE",
  "README.md",
  "CHANGELOG.md",
]
keywords = ["remotefs", "ssh-client", "scp-client", "sftp-client"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remotefs-rs/remotefs-rs-ssh"
rust-version = "1.89.0"
description = "remotefs SSH client library"

[features]
default = ["find", "libssh2"]
find = ["remotefs/find"]
libssh = ["dep:libssh-rs"]
libssh-vendored = ["libssh", "libssh-rs/vendored", "libssh-rs/vendored-openssl"]
libssh2 = ["dep:ssh2"]
libssh2-vendored = ["libssh2", "ssh2/vendored-openssl"]
no-log = ["log/max_level_off"]
russh = ["dep:russh", "dep:russh-sftp", "dep:tokio"]

[dependencies]
chrono = "0.4"
lazy-regex = "3"
libssh-rs = { version = "0.3", optional = true }
log = "0.4"
remotefs = "0.3"
russh = { version = "0.63", optional = true }
russh-sftp = { version = "2", optional = true }
ssh2 = { version = "0.9", optional = true }
ssh2-config = "0.7"
tokio = { version = "1", default-features = false, features = ["rt"], optional = true }

[dev-dependencies]
criterion = "0.8"
env_logger = "0.11"
pretty_assertions = "1"
rand = "0.10"
rpassword = "7"
tempfile = "3"
testcontainers = { version = "0.28", features = ["blocking"] }

[target."cfg(target_os = \"windows\")"]
[target."cfg(target_os = \"windows\")".dependencies]
path-slash = "0.2"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "libssh2"
harness = false
required-features = ["libssh2"]

[[bench]]
name = "libssh"
harness = false
required-features = ["libssh"]

[[bench]]
name = "russh"
harness = false
required-features = ["russh"]

[[example]]
name = "scp"
required-features = ["libssh2"]
path = "examples/scp.rs"

[[example]]
name = "scp-russh"
required-features = ["russh"]
path = "examples/scp-russh.rs"

[[example]]
name = "sftp"
required-features = ["libssh2"]
path = "examples/sftp.rs"

[[example]]
name = "sftp-russh"
required-features = ["russh"]
path = "examples/sftp-russh.rs"
