name: bench

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  bench:
    name: Bench (${{ matrix.features }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: [libssh, libssh2, russh]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run benchmarks
        run: cargo bench --features ${{ matrix.features }} --bench ${{ matrix.features }}
