name: Linux

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libssh2-1-dev libssl-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Build
        run: cargo build --all-features
      - name: Build (unsecure)
        run: cargo build --no-default-features
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --features find -- -Dwarnings
      - name: Run tests
        run: cargo test --all-features --features find,github-actions
        env:
          RUST_LOG: trace
